# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(913, 552)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 891, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 891, 501))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setMovable(False)
        self.tabWidget_2.setTabBarAutoHide(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 861, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.verticalLayout.addWidget(self.label_30)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_3.addWidget(self.label_31)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_2.addWidget(self.label_32)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_34 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_8.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_8.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_8.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_8.addWidget(self.label_37)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 861, 501))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_43 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_9.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_9.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_9.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_9.addWidget(self.label_46)
        self.label_47 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_9.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_9.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_9.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_9.addWidget(self.label_50)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_51 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_10.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_10.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_10.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_10.addWidget(self.label_54)
        self.label_55 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_10.addWidget(self.label_55)
        self.label_56 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_10.addWidget(self.label_56)
        self.label_57 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_10.addWidget(self.label_57)
        self.label_58 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_10.addWidget(self.label_58)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_59 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_11.addWidget(self.label_59)
        self.label_60 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_11.addWidget(self.label_60)
        self.label_61 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_11.addWidget(self.label_61)
        self.label_62 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_11.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_11.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_11.addWidget(self.label_64)
        self.label_65 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_11.addWidget(self.label_65)
        self.label_66 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_11.addWidget(self.label_66)
        self.horizontalLayout_5.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_67 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_12.addWidget(self.label_67)
        self.label_68 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_12.addWidget(self.label_68)
        self.label_69 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_12.addWidget(self.label_69)
        self.label_70 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_70.setObjectName("label_70")
        self.verticalLayout_12.addWidget(self.label_70)
        self.horizontalLayout_5.addLayout(self.verticalLayout_12)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(440, 10, 431, 69))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_41 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_6.addWidget(self.label_41)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_4.addWidget(self.label_33)
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_4.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_4.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_4.addWidget(self.label_40)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_42 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_13.addWidget(self.label_42)
        self.label_77 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_13.addWidget(self.label_77)
        self.label_78 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_13.addWidget(self.label_78)
        self.label_79 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_13.addWidget(self.label_79)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 401, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_93 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_93.sizePolicy().hasHeightForWidth())
        self.label_93.setSizePolicy(sizePolicy)
        self.label_93.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_19.addWidget(self.label_93)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_28.setAutoFillBackground(False)
        self.label_28.setScaledContents(False)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_4.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_4.addWidget(self.label_29)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_4.addWidget(self.label_24)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_4.addWidget(self.label_22)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_5.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_5.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_5.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_5.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_5.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_5.addWidget(self.lineEdit_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_85 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_85.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_85.setAutoFillBackground(False)
        self.label_85.setScaledContents(False)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_16.addWidget(self.label_85)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_86 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_17.addWidget(self.label_86)
        self.label_87 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_17.addWidget(self.label_87)
        self.label_88 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_17.addWidget(self.label_88)
        self.label_89 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_89.setObjectName("label_89")
        self.verticalLayout_17.addWidget(self.label_89)
        self.label_90 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_17.addWidget(self.label_90)
        self.label_91 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_17.addWidget(self.label_91)
        self.label_92 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_17.addWidget(self.label_92)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_18.addWidget(self.lineEdit_11)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_18.addWidget(self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_18.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_18.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_18.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_18.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_18.addWidget(self.lineEdit_17)
        self.horizontalLayout_7.addLayout(self.verticalLayout_18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_16)
        self.verticalLayout_19.addLayout(self.horizontalLayout_8)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(490, 280, 351, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_94 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_94.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_20.addWidget(self.label_94)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_95 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_95.setObjectName("label_95")
        self.horizontalLayout_9.addWidget(self.label_95)
        self.leftGripperSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.leftGripperSlider.setMaximum(10)
        self.leftGripperSlider.setPageStep(2)
        self.leftGripperSlider.setOrientation(QtCore.Qt.Horizontal)
        self.leftGripperSlider.setObjectName("leftGripperSlider")
        self.horizontalLayout_9.addWidget(self.leftGripperSlider)
        self.verticalLayout_21.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_96 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_96.setObjectName("label_96")
        self.horizontalLayout_10.addWidget(self.label_96)
        self.rightGripperSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.rightGripperSlider.setMaximum(10)
        self.rightGripperSlider.setPageStep(2)
        self.rightGripperSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rightGripperSlider.setObjectName("rightGripperSlider")
        self.horizontalLayout_10.addWidget(self.rightGripperSlider)
        self.verticalLayout_21.addLayout(self.horizontalLayout_10)
        self.verticalLayout_20.addLayout(self.verticalLayout_21)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(440, 190, 421, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.refreshButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_11.addWidget(self.refreshButton)
        self.estimateButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.estimateButton.setObjectName("estimateButton")
        self.horizontalLayout_11.addWidget(self.estimateButton)
        self.verticalLayout_23.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.setAngleButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.setAngleButton.setObjectName("setAngleButton")
        self.horizontalLayout_3.addWidget(self.setAngleButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_23.addLayout(self.horizontalLayout_3)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(440, 90, 431, 69))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_73 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_15.addWidget(self.label_73)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_74 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_12.addWidget(self.label_74)
        self.label_75 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_75.setObjectName("label_75")
        self.horizontalLayout_12.addWidget(self.label_75)
        self.label_76 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_12.addWidget(self.label_76)
        self.label_80 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_12.addWidget(self.label_80)
        self.verticalLayout_15.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_81 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_14.addWidget(self.label_81)
        self.label_82 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_82.setObjectName("label_82")
        self.horizontalLayout_14.addWidget(self.label_82)
        self.label_137 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_137.setObjectName("label_137")
        self.horizontalLayout_14.addWidget(self.label_137)
        self.label_138 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_138.setObjectName("label_138")
        self.horizontalLayout_14.addWidget(self.label_138)
        self.verticalLayout_15.addLayout(self.horizontalLayout_14)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_6)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 871, 481))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_71 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_71.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_71.setObjectName("label_71")
        self.verticalLayout_13.addWidget(self.label_71)
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_13.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_13.addWidget(self.radioButton_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_16.addWidget(self.radioButton_3)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_16.addWidget(self.checkBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.setRPButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.setRPButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.setRPButton.setObjectName("setRPButton")
        self.verticalLayout_13.addWidget(self.setRPButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_72 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_72.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_14.addWidget(self.label_72)
        self.connectRPButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectRPButton.sizePolicy().hasHeightForWidth())
        self.connectRPButton.setSizePolicy(sizePolicy)
        self.connectRPButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.connectRPButton.setAutoFillBackground(False)
        self.connectRPButton.setCheckable(False)
        self.connectRPButton.setObjectName("connectRPButton")
        self.verticalLayout_14.addWidget(self.connectRPButton, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.playButton = QtWidgets.QPushButton(self.tab_3)
        self.playButton.setGeometry(QtCore.QRect(20, 280, 241, 101))
        self.playButton.setObjectName("playButton")
        self.recordButton = QtWidgets.QPushButton(self.tab_3)
        self.recordButton.setGeometry(QtCore.QRect(20, 20, 241, 101))
        self.recordButton.setObjectName("recordButton")
        self.stopButton = QtWidgets.QPushButton(self.tab_3)
        self.stopButton.setGeometry(QtCore.QRect(20, 150, 241, 101))
        self.stopButton.setObjectName("stopButton")
        self.label_139 = QtWidgets.QLabel(self.tab_3)
        self.label_139.setGeometry(QtCore.QRect(30, 400, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_139.setFont(font)
        self.label_139.setObjectName("label_139")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_7)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 891, 501))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.tab_8)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 0, 891, 471))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.groupBox_24 = QtWidgets.QGroupBox(self.tab_17)
        self.groupBox_24.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_24.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_24.setObjectName("groupBox_24")
        self.label_112 = QtWidgets.QLabel(self.groupBox_24)
        self.label_112.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_112.setObjectName("label_112")
        self.velocityGraph_lb = PlotWidget(self.groupBox_24)
        self.velocityGraph_lb.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_lb.setObjectName("velocityGraph_lb")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab_17)
        self.groupBox_22.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_22.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_22.setObjectName("groupBox_22")
        self.label_110 = QtWidgets.QLabel(self.groupBox_22)
        self.label_110.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_110.setObjectName("label_110")
        self.voltageGraph_lb = PlotWidget(self.groupBox_22)
        self.voltageGraph_lb.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_lb.setObjectName("voltageGraph_lb")
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_17)
        self.groupBox_23.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_23.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_23.setObjectName("groupBox_23")
        self.label_111 = QtWidgets.QLabel(self.groupBox_23)
        self.label_111.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_111.setObjectName("label_111")
        self.angleGraph_lb = PlotWidget(self.groupBox_23)
        self.angleGraph_lb.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_lb.setObjectName("angleGraph_lb")
        self.tabWidget_5.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.groupBox_25 = QtWidgets.QGroupBox(self.tab_18)
        self.groupBox_25.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_25.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_25.setObjectName("groupBox_25")
        self.label_113 = QtWidgets.QLabel(self.groupBox_25)
        self.label_113.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_113.setObjectName("label_113")
        self.voltageGraph_l1 = PlotWidget(self.groupBox_25)
        self.voltageGraph_l1.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_l1.setObjectName("voltageGraph_l1")
        self.groupBox_26 = QtWidgets.QGroupBox(self.tab_18)
        self.groupBox_26.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_26.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_26.setObjectName("groupBox_26")
        self.label_114 = QtWidgets.QLabel(self.groupBox_26)
        self.label_114.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_114.setObjectName("label_114")
        self.angleGraph_l1 = PlotWidget(self.groupBox_26)
        self.angleGraph_l1.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_l1.setObjectName("angleGraph_l1")
        self.groupBox_27 = QtWidgets.QGroupBox(self.tab_18)
        self.groupBox_27.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_27.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_27.setObjectName("groupBox_27")
        self.label_115 = QtWidgets.QLabel(self.groupBox_27)
        self.label_115.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_115.setObjectName("label_115")
        self.velocityGraph_l1 = PlotWidget(self.groupBox_27)
        self.velocityGraph_l1.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_l1.setObjectName("velocityGraph_l1")
        self.tabWidget_5.addTab(self.tab_18, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.groupBox_28 = QtWidgets.QGroupBox(self.tab_19)
        self.groupBox_28.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_28.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_28.setObjectName("groupBox_28")
        self.label_116 = QtWidgets.QLabel(self.groupBox_28)
        self.label_116.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_116.setObjectName("label_116")
        self.voltageGraph_l2 = PlotWidget(self.groupBox_28)
        self.voltageGraph_l2.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_l2.setObjectName("voltageGraph_l2")
        self.groupBox_29 = QtWidgets.QGroupBox(self.tab_19)
        self.groupBox_29.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_29.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_29.setObjectName("groupBox_29")
        self.label_117 = QtWidgets.QLabel(self.groupBox_29)
        self.label_117.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_117.setObjectName("label_117")
        self.angleGraph_l2 = PlotWidget(self.groupBox_29)
        self.angleGraph_l2.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_l2.setObjectName("angleGraph_l2")
        self.groupBox_30 = QtWidgets.QGroupBox(self.tab_19)
        self.groupBox_30.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_30.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_30.setObjectName("groupBox_30")
        self.label_118 = QtWidgets.QLabel(self.groupBox_30)
        self.label_118.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_118.setObjectName("label_118")
        self.velocityGraph_l2 = PlotWidget(self.groupBox_30)
        self.velocityGraph_l2.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_l2.setObjectName("velocityGraph_l2")
        self.tabWidget_5.addTab(self.tab_19, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.groupBox_31 = QtWidgets.QGroupBox(self.tab_20)
        self.groupBox_31.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_31.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_31.setObjectName("groupBox_31")
        self.label_119 = QtWidgets.QLabel(self.groupBox_31)
        self.label_119.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_119.setObjectName("label_119")
        self.voltageGraph_l3 = PlotWidget(self.groupBox_31)
        self.voltageGraph_l3.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_l3.setObjectName("voltageGraph_l3")
        self.groupBox_32 = QtWidgets.QGroupBox(self.tab_20)
        self.groupBox_32.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_32.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_32.setObjectName("groupBox_32")
        self.label_120 = QtWidgets.QLabel(self.groupBox_32)
        self.label_120.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_120.setObjectName("label_120")
        self.angleGraph_l3 = PlotWidget(self.groupBox_32)
        self.angleGraph_l3.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_l3.setObjectName("angleGraph_l3")
        self.groupBox_33 = QtWidgets.QGroupBox(self.tab_20)
        self.groupBox_33.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_33.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_33.setObjectName("groupBox_33")
        self.label_121 = QtWidgets.QLabel(self.groupBox_33)
        self.label_121.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_121.setObjectName("label_121")
        self.velocityGraph_l3 = PlotWidget(self.groupBox_33)
        self.velocityGraph_l3.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_l3.setObjectName("velocityGraph_l3")
        self.tabWidget_5.addTab(self.tab_20, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.groupBox_34 = QtWidgets.QGroupBox(self.tab_21)
        self.groupBox_34.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_34.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_34.setObjectName("groupBox_34")
        self.label_122 = QtWidgets.QLabel(self.groupBox_34)
        self.label_122.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_122.setObjectName("label_122")
        self.voltageGraph_l4 = PlotWidget(self.groupBox_34)
        self.voltageGraph_l4.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_l4.setObjectName("voltageGraph_l4")
        self.groupBox_35 = QtWidgets.QGroupBox(self.tab_21)
        self.groupBox_35.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_35.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_35.setObjectName("groupBox_35")
        self.label_123 = QtWidgets.QLabel(self.groupBox_35)
        self.label_123.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_123.setObjectName("label_123")
        self.angleGraph_l4 = PlotWidget(self.groupBox_35)
        self.angleGraph_l4.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_l4.setObjectName("angleGraph_l4")
        self.groupBox_36 = QtWidgets.QGroupBox(self.tab_21)
        self.groupBox_36.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_36.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_36.setObjectName("groupBox_36")
        self.label_124 = QtWidgets.QLabel(self.groupBox_36)
        self.label_124.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_124.setObjectName("label_124")
        self.velocityGraph_l4 = PlotWidget(self.groupBox_36)
        self.velocityGraph_l4.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_l4.setObjectName("velocityGraph_l4")
        self.tabWidget_5.addTab(self.tab_21, "")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.groupBox_37 = QtWidgets.QGroupBox(self.tab_22)
        self.groupBox_37.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_37.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_37.setObjectName("groupBox_37")
        self.label_125 = QtWidgets.QLabel(self.groupBox_37)
        self.label_125.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_125.setObjectName("label_125")
        self.voltageGraph_l5 = PlotWidget(self.groupBox_37)
        self.voltageGraph_l5.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_l5.setObjectName("voltageGraph_l5")
        self.groupBox_38 = QtWidgets.QGroupBox(self.tab_22)
        self.groupBox_38.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_38.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_38.setObjectName("groupBox_38")
        self.label_126 = QtWidgets.QLabel(self.groupBox_38)
        self.label_126.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_126.setObjectName("label_126")
        self.angleGraph_l5 = PlotWidget(self.groupBox_38)
        self.angleGraph_l5.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_l5.setObjectName("angleGraph_l5")
        self.groupBox_39 = QtWidgets.QGroupBox(self.tab_22)
        self.groupBox_39.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_39.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_39.setObjectName("groupBox_39")
        self.label_127 = QtWidgets.QLabel(self.groupBox_39)
        self.label_127.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_127.setObjectName("label_127")
        self.velocityGraph_l5 = PlotWidget(self.groupBox_39)
        self.velocityGraph_l5.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_l5.setObjectName("velocityGraph_l5")
        self.tabWidget_5.addTab(self.tab_22, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.groupBox_40 = QtWidgets.QGroupBox(self.tab_23)
        self.groupBox_40.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_40.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_40.setObjectName("groupBox_40")
        self.label_128 = QtWidgets.QLabel(self.groupBox_40)
        self.label_128.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_128.setObjectName("label_128")
        self.voltageGraph_l6 = PlotWidget(self.groupBox_40)
        self.voltageGraph_l6.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_l6.setObjectName("voltageGraph_l6")
        self.groupBox_41 = QtWidgets.QGroupBox(self.tab_23)
        self.groupBox_41.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_41.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_41.setObjectName("groupBox_41")
        self.label_129 = QtWidgets.QLabel(self.groupBox_41)
        self.label_129.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_129.setObjectName("label_129")
        self.angleGraph_l6 = PlotWidget(self.groupBox_41)
        self.angleGraph_l6.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_l6.setObjectName("angleGraph_l6")
        self.groupBox_42 = QtWidgets.QGroupBox(self.tab_23)
        self.groupBox_42.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_42.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_42.setObjectName("groupBox_42")
        self.label_130 = QtWidgets.QLabel(self.groupBox_42)
        self.label_130.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_130.setObjectName("label_130")
        self.velocityGraph_l6 = PlotWidget(self.groupBox_42)
        self.velocityGraph_l6.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_l6.setObjectName("velocityGraph_l6")
        self.tabWidget_5.addTab(self.tab_23, "")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_9)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 891, 471))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_19.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_19.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_19.setObjectName("groupBox_19")
        self.label_107 = QtWidgets.QLabel(self.groupBox_19)
        self.label_107.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_107.setObjectName("label_107")
        self.voltageGraph_rb = PlotWidget(self.groupBox_19)
        self.voltageGraph_rb.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_rb.setObjectName("voltageGraph_rb")
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_20.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_20.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_20.setObjectName("groupBox_20")
        self.label_108 = QtWidgets.QLabel(self.groupBox_20)
        self.label_108.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_108.setObjectName("label_108")
        self.angleGraph_rb = PlotWidget(self.groupBox_20)
        self.angleGraph_rb.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_rb.setObjectName("angleGraph_rb")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_10)
        self.groupBox_21.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_21.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_21.setObjectName("groupBox_21")
        self.label_109 = QtWidgets.QLabel(self.groupBox_21)
        self.label_109.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_109.setObjectName("label_109")
        self.velocityGraph_rb = PlotWidget(self.groupBox_21)
        self.velocityGraph_rb.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_rb.setObjectName("velocityGraph_rb")
        self.tabWidget_4.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_16.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_16.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_16.setObjectName("groupBox_16")
        self.label_104 = QtWidgets.QLabel(self.groupBox_16)
        self.label_104.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_104.setObjectName("label_104")
        self.voltageGraph_r1 = PlotWidget(self.groupBox_16)
        self.voltageGraph_r1.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_r1.setObjectName("voltageGraph_r1")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_17.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_17.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_17.setObjectName("groupBox_17")
        self.label_105 = QtWidgets.QLabel(self.groupBox_17)
        self.label_105.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_105.setObjectName("label_105")
        self.angleGraph_r1 = PlotWidget(self.groupBox_17)
        self.angleGraph_r1.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_r1.setObjectName("angleGraph_r1")
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_18.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_18.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_18.setObjectName("groupBox_18")
        self.label_106 = QtWidgets.QLabel(self.groupBox_18)
        self.label_106.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_106.setObjectName("label_106")
        self.velocityGraph_r1 = PlotWidget(self.groupBox_18)
        self.velocityGraph_r1.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_r1.setObjectName("velocityGraph_r1")
        self.tabWidget_4.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_13.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_13.setObjectName("groupBox_13")
        self.label_101 = QtWidgets.QLabel(self.groupBox_13)
        self.label_101.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_101.setObjectName("label_101")
        self.voltageGraph_r2 = PlotWidget(self.groupBox_13)
        self.voltageGraph_r2.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_r2.setObjectName("voltageGraph_r2")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_14.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_14.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_14.setObjectName("groupBox_14")
        self.label_102 = QtWidgets.QLabel(self.groupBox_14)
        self.label_102.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_102.setObjectName("label_102")
        self.angleGraph_r2 = PlotWidget(self.groupBox_14)
        self.angleGraph_r2.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_r2.setObjectName("angleGraph_r2")
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_15.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_15.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_103 = QtWidgets.QLabel(self.groupBox_15)
        self.label_103.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_103.setObjectName("label_103")
        self.velocityGraph_r2 = PlotWidget(self.groupBox_15)
        self.velocityGraph_r2.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_r2.setObjectName("velocityGraph_r2")
        self.tabWidget_4.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox_10.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_10.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_98 = QtWidgets.QLabel(self.groupBox_10)
        self.label_98.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_98.setObjectName("label_98")
        self.voltageGraph_r3 = PlotWidget(self.groupBox_10)
        self.voltageGraph_r3.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_r3.setObjectName("voltageGraph_r3")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_99 = QtWidgets.QLabel(self.groupBox_11)
        self.label_99.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_99.setObjectName("label_99")
        self.angleGraph_r3 = PlotWidget(self.groupBox_11)
        self.angleGraph_r3.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_r3.setObjectName("angleGraph_r3")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_13)
        self.groupBox_12.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_100 = QtWidgets.QLabel(self.groupBox_12)
        self.label_100.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_100.setObjectName("label_100")
        self.velocityGraph_r3 = PlotWidget(self.groupBox_12)
        self.velocityGraph_r3.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_r3.setObjectName("velocityGraph_r3")
        self.tabWidget_4.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_14)
        self.groupBox_7.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_83 = QtWidgets.QLabel(self.groupBox_7)
        self.label_83.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_83.setObjectName("label_83")
        self.velocityGraph_r4 = PlotWidget(self.groupBox_7)
        self.velocityGraph_r4.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_r4.setObjectName("velocityGraph_r4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_14)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_84 = QtWidgets.QLabel(self.groupBox_8)
        self.label_84.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_84.setObjectName("label_84")
        self.angleGraph_r4 = PlotWidget(self.groupBox_8)
        self.angleGraph_r4.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_r4.setObjectName("angleGraph_r4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_14)
        self.groupBox_9.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_97 = QtWidgets.QLabel(self.groupBox_9)
        self.label_97.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_97.setObjectName("label_97")
        self.voltageGraph_r4 = PlotWidget(self.groupBox_9)
        self.voltageGraph_r4.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_r4.setObjectName("voltageGraph_r4")
        self.tabWidget_4.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.groupBox_43 = QtWidgets.QGroupBox(self.tab_15)
        self.groupBox_43.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_43.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_43.setObjectName("groupBox_43")
        self.label_131 = QtWidgets.QLabel(self.groupBox_43)
        self.label_131.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_131.setObjectName("label_131")
        self.voltageGraph_r5 = PlotWidget(self.groupBox_43)
        self.voltageGraph_r5.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_r5.setObjectName("voltageGraph_r5")
        self.groupBox_44 = QtWidgets.QGroupBox(self.tab_15)
        self.groupBox_44.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_44.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_44.setObjectName("groupBox_44")
        self.label_132 = QtWidgets.QLabel(self.groupBox_44)
        self.label_132.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_132.setObjectName("label_132")
        self.angleGraph_r5 = PlotWidget(self.groupBox_44)
        self.angleGraph_r5.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_r5.setObjectName("angleGraph_r5")
        self.groupBox_45 = QtWidgets.QGroupBox(self.tab_15)
        self.groupBox_45.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_45.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_45.setObjectName("groupBox_45")
        self.label_133 = QtWidgets.QLabel(self.groupBox_45)
        self.label_133.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_133.setObjectName("label_133")
        self.velocityGraph_r5 = PlotWidget(self.groupBox_45)
        self.velocityGraph_r5.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_r5.setObjectName("velocityGraph_r5")
        self.tabWidget_4.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.groupBox_46 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_46.setGeometry(QtCore.QRect(300, 150, 280, 290))
        self.groupBox_46.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_46.setObjectName("groupBox_46")
        self.label_134 = QtWidgets.QLabel(self.groupBox_46)
        self.label_134.setGeometry(QtCore.QRect(80, 240, 171, 17))
        self.label_134.setObjectName("label_134")
        self.voltageGraph_r6 = PlotWidget(self.groupBox_46)
        self.voltageGraph_r6.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.voltageGraph_r6.setObjectName("voltageGraph_r6")
        self.groupBox_47 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_47.setGeometry(QtCore.QRect(0, 0, 280, 290))
        self.groupBox_47.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_47.setObjectName("groupBox_47")
        self.label_135 = QtWidgets.QLabel(self.groupBox_47)
        self.label_135.setGeometry(QtCore.QRect(80, 230, 171, 17))
        self.label_135.setObjectName("label_135")
        self.angleGraph_r6 = PlotWidget(self.groupBox_47)
        self.angleGraph_r6.setGeometry(QtCore.QRect(10, 20, 251, 191))
        self.angleGraph_r6.setObjectName("angleGraph_r6")
        self.groupBox_48 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_48.setGeometry(QtCore.QRect(600, 10, 280, 290))
        self.groupBox_48.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_48.setObjectName("groupBox_48")
        self.label_136 = QtWidgets.QLabel(self.groupBox_48)
        self.label_136.setGeometry(QtCore.QRect(70, 240, 181, 17))
        self.label_136.setObjectName("label_136")
        self.velocityGraph_r6 = PlotWidget(self.groupBox_48)
        self.velocityGraph_r6.setGeometry(QtCore.QRect(10, 30, 251, 191))
        self.velocityGraph_r6.setObjectName("velocityGraph_r6")
        self.tabWidget_4.addTab(self.tab_16, "")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName("tab_24")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_24)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 861, 481))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.cam_view_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.cam_view_1.setMinimumSize(QtCore.QSize(50, 50))
        self.cam_view_1.setText("")
        self.cam_view_1.setPixmap(QtGui.QPixmap("dog.jpg"))
        self.cam_view_1.setScaledContents(True)
        self.cam_view_1.setObjectName("cam_view_1")
        self.horizontalLayout_15.addWidget(self.cam_view_1)
        self.tabWidget.addTab(self.tab_24, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(5)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_30.setText(_translate("Dialog", "Joint Name"))
        self.label_2.setText(_translate("Dialog", "Joint0"))
        self.label.setText(_translate("Dialog", "Joint1"))
        self.label_4.setText(_translate("Dialog", "Joint2"))
        self.label_3.setText(_translate("Dialog", "Joint3"))
        self.label_5.setText(_translate("Dialog", "Joint4"))
        self.label_7.setText(_translate("Dialog", "Joint5"))
        self.label_6.setText(_translate("Dialog", "Joint6"))
        self.label_31.setText(_translate("Dialog", "Angle(radian)"))
        self.label_15.setText(_translate("Dialog", "j0a"))
        self.label_16.setText(_translate("Dialog", "j1a"))
        self.label_17.setText(_translate("Dialog", "j2a"))
        self.label_18.setText(_translate("Dialog", "j3a"))
        self.label_19.setText(_translate("Dialog", "j4a"))
        self.label_20.setText(_translate("Dialog", "j5a"))
        self.label_21.setText(_translate("Dialog", "j6a"))
        self.label_32.setText(_translate("Dialog", "Velocity(rad/s)"))
        self.label_8.setText(_translate("Dialog", "j0v"))
        self.label_9.setText(_translate("Dialog", "j1v"))
        self.label_10.setText(_translate("Dialog", "j2v"))
        self.label_11.setText(_translate("Dialog", "j3v"))
        self.label_12.setText(_translate("Dialog", "j4v"))
        self.label_13.setText(_translate("Dialog", "j5v"))
        self.label_14.setText(_translate("Dialog", "j6v"))
        self.label_34.setText(_translate("Dialog", "Cartesian Pose"))
        self.label_35.setText(_translate("Dialog", "Xpose"))
        self.label_36.setText(_translate("Dialog", "Ypose"))
        self.label_37.setText(_translate("Dialog", "Zpose"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Dialog", "Left Arm"))
        self.label_43.setText(_translate("Dialog", "Joint Name"))
        self.label_44.setText(_translate("Dialog", "Joint0"))
        self.label_45.setText(_translate("Dialog", "Joint1"))
        self.label_46.setText(_translate("Dialog", "Joint2"))
        self.label_47.setText(_translate("Dialog", "Joint3"))
        self.label_48.setText(_translate("Dialog", "Joint4"))
        self.label_49.setText(_translate("Dialog", "Joint5"))
        self.label_50.setText(_translate("Dialog", "Joint6"))
        self.label_51.setText(_translate("Dialog", "Angle(radian)"))
        self.label_52.setText(_translate("Dialog", "j0a"))
        self.label_53.setText(_translate("Dialog", "j1a"))
        self.label_54.setText(_translate("Dialog", "j2a"))
        self.label_55.setText(_translate("Dialog", "j3a"))
        self.label_56.setText(_translate("Dialog", "j4a"))
        self.label_57.setText(_translate("Dialog", "j5a"))
        self.label_58.setText(_translate("Dialog", "j6a"))
        self.label_59.setText(_translate("Dialog", "Velocity(rad/s)"))
        self.label_60.setText(_translate("Dialog", "j0v"))
        self.label_61.setText(_translate("Dialog", "j1v"))
        self.label_62.setText(_translate("Dialog", "j2v"))
        self.label_63.setText(_translate("Dialog", "j3v"))
        self.label_64.setText(_translate("Dialog", "j4v"))
        self.label_65.setText(_translate("Dialog", "j5v"))
        self.label_66.setText(_translate("Dialog", "j6v"))
        self.label_67.setText(_translate("Dialog", "Cartesian Pose"))
        self.label_68.setText(_translate("Dialog", "Xpose"))
        self.label_69.setText(_translate("Dialog", "Ypose"))
        self.label_70.setText(_translate("Dialog", "Zpose"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "Right Arm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Info"))
        self.label_41.setText(_translate("Dialog", "Current Cartesian Position"))
        self.label_33.setText(_translate("Dialog", "Left"))
        self.label_38.setText(_translate("Dialog", "Xpose"))
        self.label_39.setText(_translate("Dialog", "Ypose"))
        self.label_40.setText(_translate("Dialog", "Zpose"))
        self.label_42.setText(_translate("Dialog", "Right"))
        self.label_77.setText(_translate("Dialog", "Xpose"))
        self.label_78.setText(_translate("Dialog", "Ypose"))
        self.label_79.setText(_translate("Dialog", "Zpose"))
        self.label_93.setText(_translate("Dialog", "Angle Control"))
        self.label_28.setText(_translate("Dialog", "Left Arm"))
        self.label_23.setText(_translate("Dialog", "Joint0"))
        self.label_25.setText(_translate("Dialog", "Joint1"))
        self.label_26.setText(_translate("Dialog", "Joint2"))
        self.label_29.setText(_translate("Dialog", "Joint3"))
        self.label_27.setText(_translate("Dialog", "Joint4"))
        self.label_24.setText(_translate("Dialog", "Joint5"))
        self.label_22.setText(_translate("Dialog", "Joint6"))
        self.label_85.setText(_translate("Dialog", "Right Arm"))
        self.label_86.setText(_translate("Dialog", "Joint0"))
        self.label_87.setText(_translate("Dialog", "Joint1"))
        self.label_88.setText(_translate("Dialog", "Joint2"))
        self.label_89.setText(_translate("Dialog", "Joint3"))
        self.label_90.setText(_translate("Dialog", "Joint4"))
        self.label_91.setText(_translate("Dialog", "Joint5"))
        self.label_92.setText(_translate("Dialog", "Joint6"))
        self.label_94.setText(_translate("Dialog", "Gripper Control"))
        self.label_95.setText(_translate("Dialog", " Left  "))
        self.label_96.setText(_translate("Dialog", " Right "))
        self.refreshButton.setText(_translate("Dialog", "Get Current Angle"))
        self.estimateButton.setText(_translate("Dialog", "Get Estimated Position"))
        self.setAngleButton.setText(_translate("Dialog", "Set Angle"))
        self.pushButton_2.setText(_translate("Dialog", "Home Kinova Arm"))
        self.label_73.setText(_translate("Dialog", "Estimate Cartesian Position"))
        self.label_74.setText(_translate("Dialog", "Left"))
        self.label_75.setText(_translate("Dialog", "Xpose"))
        self.label_76.setText(_translate("Dialog", "Ypose"))
        self.label_80.setText(_translate("Dialog", "Zpose"))
        self.label_81.setText(_translate("Dialog", "Right"))
        self.label_82.setText(_translate("Dialog", "Xpose"))
        self.label_137.setText(_translate("Dialog", "Ypose"))
        self.label_138.setText(_translate("Dialog", "Zpose"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Control"))
        self.label_71.setText(_translate("Dialog", "Control Mode"))
        self.radioButton.setText(_translate("Dialog", "Only left arm"))
        self.radioButton_2.setText(_translate("Dialog", "Only right arm"))
        self.radioButton_3.setText(_translate("Dialog", "Both arms"))
        self.checkBox.setText(_translate("Dialog", "Mirror"))
        self.setRPButton.setText(_translate("Dialog", "Confirm"))
        self.label_72.setText(_translate("Dialog", "TextLabel"))
        self.connectRPButton.setText(_translate("Dialog", "Enable/Disable Connection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Robopuppet Settings"))
        self.playButton.setText(_translate("Dialog", "Play"))
        self.recordButton.setText(_translate("Dialog", "Record"))
        self.stopButton.setText(_translate("Dialog", "Stop"))
        self.label_139.setText(_translate("Dialog", "*Play recorded motion will automatically disable robopuppet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Learn"))
        self.groupBox_24.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_112.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.groupBox_22.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_110.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_23.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_111.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_17), _translate("Dialog", "Base"))
        self.groupBox_25.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_113.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_26.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_114.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_27.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_115.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_18), _translate("Dialog", "Joint 1"))
        self.groupBox_28.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_116.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_29.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_117.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_30.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_118.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_19), _translate("Dialog", "Joint 2"))
        self.groupBox_31.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_119.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_32.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_120.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_33.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_121.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_20), _translate("Dialog", "Joint 3"))
        self.groupBox_34.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_122.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_35.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_123.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_36.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_124.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_21), _translate("Dialog", "Joint 4"))
        self.groupBox_37.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_125.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_38.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_126.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_39.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_127.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_22), _translate("Dialog", "Joint 5"))
        self.groupBox_40.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_128.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_41.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_129.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_42.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_130.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_23), _translate("Dialog", "Joint 6"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("Dialog", "Left Arm"))
        self.groupBox_19.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_107.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_20.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_108.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_21.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_109.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("Dialog", "Base"))
        self.groupBox_16.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_104.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_17.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_105.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_18.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_106.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("Dialog", "Joint 1"))
        self.groupBox_13.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_101.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_14.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_102.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_15.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_103.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), _translate("Dialog", "Joint 2"))
        self.groupBox_10.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_98.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_11.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_99.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_12.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_100.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_13), _translate("Dialog", "Joint 3"))
        self.groupBox_7.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_83.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.groupBox_8.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_84.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_9.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_97.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_14), _translate("Dialog", "Joint 4"))
        self.groupBox_43.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_131.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_44.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_132.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_45.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_133.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_15), _translate("Dialog", "Joint 5"))
        self.groupBox_46.setTitle(_translate("Dialog", "Joint Voltage"))
        self.label_134.setText(_translate("Dialog", "Joint Voltage Over Time(s)"))
        self.groupBox_47.setTitle(_translate("Dialog", "Joint Angle"))
        self.label_135.setText(_translate("Dialog", "Joint Angle Over Time(s)"))
        self.groupBox_48.setTitle(_translate("Dialog", "Joint Velocity"))
        self.label_136.setText(_translate("Dialog", "Joint Velocity Over Time(s)"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_16), _translate("Dialog", "Joint 6"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("Dialog", "Right Arm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Plots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_24), _translate("Dialog", "Camera View"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

